repoUrl: https://github.com/aws-samples
targetRevision: main
account: 123456789
region: us-east-1
serviceAccount:
  name: triton-sa

image:
  # This is overridden by CDK bootstrapValues with the actual ECR URI
  imageName: "${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/triton-fraud-detection:latest"
  pullPolicy: IfNotPresent
  numGpus: 1

bucketName: bucket
namespace: triton


